global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rails-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:3000']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121'] 